(ns ops-panel.core
  (:require [reagent.core :as r]))

(defn app []
  [:div {:style {:color :red}} "This humble red text is generated by reagent."])

(defn ^:export main []
  (r/render [app]
            (js/document.getElementById "app_container")))
